# GitHub Action - CI Pipeline dedicated to scan vulnerability on a Docker Image
# Capgemini - v1.0 - Xavier BRASSOUD <xavier.brassoud@capgemini.com>
#

name: CI - Scan Docker Image

on:
  push:
  pull_request:
    branches:
      - '**'

jobs:
  ci-scan-docker-image:
    runs-on: ubuntu-latest

    steps:

    ##############################################################################
    ### STEP 1 : Run vulnerability scanner on container : vulnerables/web-dvwa ###
    ##############################################################################
    - name: Run Trivy vulnerability scanner on vulnerables/web-dvwa Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: vulnerables/web-dvwa
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results-docker.sarif'
    
    ###########################################################
    ### STEP 2 : Upload Trivy vulnerability to Security Tab ###
    ###########################################################
    - name: Upload Trivy vulnerability to GitHub Security Tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: trivy-results-docker.sarif
